### PR TITLE
Update main website picture

### PR DESCRIPTION
**Pull request by leonardpahlke**
picture created once by us for the WG ENV, ref: https://www.cncf.io/blog/2022/05/31/cncf-wg-environmental-sustainability/

### CODE REVIEW

**Review by cjyabraham — CHANGES_REQUESTED** [review]
The image is 1.52MB. Could you try resizing/compressing to get it down to, say, under 500K so that we can make sure the homepage continues to load quickly?

If you'd prefer, you could merge the PR and then I will fix the image.

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
You can install https://github.com/apps/imgbot and let it reduce the images automatically once in main :)

**Comment by leonardpahlke** [comment]
resized ✅ 1.52MB -> 330.5 kb

**Comment by leonardpahlke** [comment]
> You can install https://github.com/apps/imgbot and let it reduce the images automatically once in main :)

👍

**Comment by cjyabraham** [comment]
One other comment on this image, the background of the image is white, while the background of the site is #fdfdfd, so you can see a faint line between the background of the image and the rest of the site. Ideally, this kind of image would look best as an SVG with a transparent background. Alternatively you could change the background to #fdfdfd so that it merges with the site color seamlessly. Alternatively, you can just ignore me if this is too fine-grained feedback ;)

**Pull request merged**
