### PR TITLE
CI Fixes

### LINKED ISSUE #156: [CI] GitHub actions are passing despite fatal errors in workflow scripts
It seems that Setup, and the other actions that depend on it, are failing. For example, see this log:

- https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801

Here is an excerpt:

```nocode
Run make lint
Running lint...


Creating network "tag-env-sustainability_default" with the default driver
Creating tag-env-sustainability_lint_run ... 
Creating tag-env-sustainability_lint_run ... done

added [5](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:6)9 packages in 2s

npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 
1[7](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:8) packages are looking for funding
  run `npm fund` for details
fatal: detected dubious ownership in repository at '/usr/src/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/src/app
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
...
```

Checks can be setup more directly via NPM dependencies and scripts. This site is small enough that it probably isn't worth trying to optimize checks over only changed files. (My 2 cents :))

/cc @cjyabraham @nate-double-u

### PR DESCRIPTION
**Pull request by Azanul**
Fixes #156

### CODE REVIEW

**Comment by chalin** [comment]
Hi @Azanul - thanks for this, but because reactivating checks also implies the need to fix the reported issues (otherwise PR checks will fail), I've decided to tackle #156 step-wise by reactivating each check separately (and fixing the reported issues at the same time). For example, see #169. /cc @cjyabraham

**Comment by Azanul** [comment]
> Hi @Azanul - thanks for this, but because reactivating checks also implies the need to fix the reported issues (otherwise PR checks will fail), I've decided to tackle #156 step-wise by reactivating each check separately (and fixing the reported issues at the same time). For example, see #169. /cc @cjyabraham

This PR mostly contains changes common for all checks i.e., docker removal, failing check on script errors. Do you want me to distribute it across multiple PRs along with respective check fixes, like you've done with #169 ?

**Comment by chalin** [comment]
Thanks for the offer. I suggest that we wait and see what happens with #169 first. I'm unsure about the other checks yet: I _might_ bring in link checking next -- but that change will be based on how it's handled in some other CNCF projects.

**Comment by guidemetothemoon** [comment]
@Azanul @chalin we have recently had a larger refactoring in the repository to properly stabilize the workflow for content QA validation with tools like `markdownlint`, `cspell` and `markdown-link-checker.` As part of this refactoring all the validations have been moved away from Bash scripts into a single GitHub workflow where those validations now run as GitHub Actions. This will simplify the maintenance of the workflow and will make any potential errors more visible and transparent. You can find more information about refactoring in the original PR #269 and the documentation: https://github.com/cncf/tag-env-sustainability/blob/main/writing-style.md#pull-request-quality-checks

Due to this refactoring current PR is no longer applicable and we will therefore be closing it. Don't hesitate to reach out if anything is unclear or if you have any questions.

Thank you so much for your time and effort in the attempt to fix the original implementation, @Azanul - even though it wasn't merged due to a larger, more long-term optimization we nevertheless see your effort and appreciate it! Don't hesitate to check out any other open issues that we have in the repo if you would like to keep contributing 🙌

**Pull request closed without merging**
