### PR TITLE
Add survey link to readme

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

/cc @mkorbi @catblade

### CODE REVIEW

**Comment by amye** [comment]
Given as this will likely close in the next ~2 weeks, probably not?

**Comment by catblade** [comment]
@amye  we had discussed closing on the 25th of November.  Temporary-but may get us traffic.  The three of us met this morning and agreed.

**Comment by catblade** [comment]
LGTM

**Comment by mkorbi** [comment]
I think we can temporarily add it, there will be enough updates soon so at one or the other we can take it out than

**Pull request merged**
