### PR TITLE
Add blog post KCCN EU 2023 WrapUp

### PR DESCRIPTION
**Pull request by leonardpahlke**
ref: tracking issue https://github.com/cncf/tag-env-sustainability/issues/85

I copied the text from our [docs file](https://docs.google.com/document/d/1EJnrSwPp-2fVnjow0WbGmyYvfyciQa9ocmKHA-TQ3yc/edit#), which has already been reviewed.

cc @catblade @mkorbi
cc @TheFoxAtWork @erinaboyd @mattfarina

I think this might be something we could share on the CNCF blog as well, WDYT? I can send an email to `pr@cncf.io`.

### CODE REVIEW

**Comment by mkorbi** [comment]
LGTM

**Review by catblade — APPROVED** [review]

**Comment by leonardpahlke** [comment]
The blog is ready. @TheFoxAtWork already reviewed it in the gdocs file. Waiting for a LGTM from @TheFoxAtWork @erinaboyd or @mattfarina to publish it.

&

> I think this might be something we could share on the CNCF blog as well, WDYT? I can send an email to pr@cncf.io.

**Review by TheFoxAtWork — APPROVED** [review]
LGTM

**Review by TheFoxAtWork — APPROVED** [review]
LGTM

**Comment by leonardpahlke** [comment]
🚀

**Pull request merged**
