### PR TITLE
[ja] Localize some _index.md pages into Japanese

### PR DESCRIPTION
**Pull request by Okabe-Junya**
tracking issue: #436

## Change List

Translate `/website/content/en`

- about/_index.md
- about/projects.md
- about/working-groups.md
- blog/_index.md
- events/_index.md

into Japanese

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
cc @kaitoii11 @naonishijima

**Comment by naonishijima** [comment]
Thanks! LGTM!

**Review by kaitoii11 — APPROVED** [review]
LGTM

**Review by leonardpahlke — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
