### PR TITLE
Refactor TAG ENV PR QA workflow

### LINKED ISSUE #156: [CI] GitHub actions are passing despite fatal errors in workflow scripts
It seems that Setup, and the other actions that depend on it, are failing. For example, see this log:

- https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801

Here is an excerpt:

```nocode
Run make lint
Running lint...


Creating network "tag-env-sustainability_default" with the default driver
Creating tag-env-sustainability_lint_run ... 
Creating tag-env-sustainability_lint_run ... done

added [5](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:6)9 packages in 2s

npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 
1[7](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:8) packages are looking for funding
  run `npm fund` for details
fatal: detected dubious ownership in repository at '/usr/src/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/src/app
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
...
```

Checks can be setup more directly via NPM dependencies and scripts. This site is small enough that it probably isn't worth trying to optimize checks over only changed files. (My 2 cents :))

/cc @cjyabraham @nate-double-u

### PR DESCRIPTION
**Pull request by guidemetothemoon**
- Moved all QA checks (linting, spelling, links) to GitHub Actions and cleaned up respective scripts, Makefile, etc. GitHub Actions are the 1-1 mapping of the original tool, i.e. either is from the same author or is referenced by the author to use when you want to run the respective tool as a GH Action. All actions run only for modified files, if there are any;
- Fixed a bunch of dead/broken links and spelling errors;
- Since cSpell hasn't worked for a while it raised a bunch of errors - improved the way it runs validations by adding custom TAG ENV dictionary with words to ignore, as well as patterns like code blocks in Markdown that we can ignore;
- Improved link check configuration and fixed findings from it;
- Added script and NPM command to install and run all the checks locally;
- Updated documentation to provide more information about QA checks we're running, how to run those locally and how to follow-up on detected issues;

Closes #156 #165

### CODE REVIEW

**Comment by leonardpahlke** [comment]
cc

**Review by leonardpahlke — APPROVED** [review]
💙 LGTM

**Comment by leonardpahlke** [comment]
@chalin is this something you are interested in? 😃 (maybe this can serve as a template to restructure some other similar repos)

**Comment by guidemetothemoon** [comment]
@leonardpahlke are we OK to merge this PR or shall I wait a bit more for feedback? 😊

**Comment by chalin** [comment]
> @chalin is this something you are interested in? 😃 (maybe this can serve as a template to restructure some other similar repos)

Maybe! Will take a look as soon as I can, but it'll likely be 24Q1 or 2 🤷🏼‍♂️

**Pull request merged**
