### PR TITLE
Reintroduce Docsy as a submodule

### PR DESCRIPTION
**Pull request by chalin**
This PR reintroduces Docsy as a submodule so that it will be easier to manage upgrades.

**Details**: this PR ...

- Contributes to #123
- Eliminates the "hardcoded" files under `website/themes/docsy`, unlinked (via a git submodule or otherwise) to any Docsy repo
- Eliminates the Bootstrap and FontAwesome (FA) submodules
- Adds https://github.com/google/docsy/commit/e67775a312f1f3ad32137423fe2b311a397f5293 as a submodule, which itself has Bootstrap and FA as submodules. For the rationale, see below.
- Updates NPM scripts to support building the website under this new setup
- There is no effective change to the rendered site. For details, read below.

**Preview**: https://deploy-preview-160--tag-env-sustainability.netlify.app/

---

### Context

The files under `website/themes/docsy` were a copy of https://github.com/google/docsy/commit/f69a99d7e38a541b74ade9850a813aee26964ba8. But that commit is a fork commit based on https://github.com/google/docsy/commit/e67775a312f1f3ad32137423fe2b311a397f5293 from the official Docsy repo, with the following overrides:

```diff
Only in tmp/docsy: .git
Only in tmp/docsy: .gitmodules
Only in themes/docsy: .hugo_build.lock
diff --exclude=userguide --exclude=vendor -r themes/docsy/assets/scss/main.scss tmp/docsy/assets/scss/main.scss
36,37c36
<     overflow: auto;
<     
---
> 
diff --exclude=userguide --exclude=vendor -r themes/docsy/layouts/partials/footer.html tmp/docsy/layouts/partials/footer.html
5c5
<       <div class="col-6 col-sm-2 text-xs-center order-sm-2">
---
>       <div class="col-6 col-sm-4 text-xs-center order-sm-2">
12c12
<       <div class="col-6 col-sm-2 text-right text-xs-center order-sm-3">
---
>       <div class="col-6 col-sm-4 text-right text-xs-center order-sm-3">
19c19
<       <div class="col-12 col-sm-8 text-center py-2 order-sm-2">
---
>       <div class="col-12 col-sm-4 text-center py-2 order-sm-2">
23,25c23,24
<     {{ with .Site.GetPage "about" }}<p class="mt-2"><a href="{{ .RelPermalink }}">{{ .Title }}</a></p>{{ end }}
<   {{ end }}
<         {{ partial "hooks/footer-end.html" . }}
---
> 		{{ with .Site.GetPage "about" }}<p class="mt-2"><a href="{{ .RelPermalink }}">{{ .Title }}</a></p>{{ end }}
> 	{{ end }}
Only in themes/docsy/layouts/partials/hooks: footer-end.html
```

Regarding the diffs shown above:

- `themes/docsy/layouts/partials/footer.html` it is completely overridden by `website/layouts/partials/footer.html` and so the diff shown above is irrelevant, as is the deletion of `footer-end.html` -- which isn't used by `website/layouts/partials/footer.html`
- [overflow: auto](https://github.com/google/docsy/commit/f69a99d7e38a541b74ade9850a813aee26964ba8) in the `footer` gets set in `website/themes/docsy/assets/scss/main.scss` (see site-diff below), gets overridden by https://github.com/cncf/tag-env-sustainability/blob/38cb8316e393d7f1ce3eb53d86e0bb642992a3f5/website/assets/scss/_footer.scss#L2-L4

  The `website/assets/scss/_footer.scss` file gets included via https://github.com/cncf/tag-env-sustainability/blob/38cb8316e393d7f1ce3eb53d86e0bb642992a3f5/website/assets/scss/_styles_project.scss#L14

  So the SCSS diff has no visible effect.

Consequently I'm going to use the official Docsy commit  https://github.com/google/docsy/commit/e67775a312f1f3ad32137423fe2b311a397f5293 as a basis for this repo's Docsy submodule.

### No change to the rendered tag-env-sustainability site

If you build the site from this PR using the following command `npm run serve:dev` (which serves to disk), you'll see only one minor diff:

```console
$ npm run serve:dev 
... # Terminate serve command once site has been generated to disk ^C
$ (cd public && git diff -- . ':(exclude)*.map')
... # Output shown below
$
```

Here's the diff output: 

```diff
diff --git a/scss/main.css b/scss/main.css
index 2b42976..c0ea53c 100644
--- a/scss/main.css
+++ b/scss/main.css
@@ -14008,8 +14008,7 @@ div.toc-header {
     border-color: #403F4C; }
 
 footer {
-  min-height: 150px;
-  overflow: auto; }
+  min-height: 150px; }
   @media (max-width: 991.98px) {
     footer {
       min-height: 200px; } }
```

The override of `footer`'s `overflow` is confirmed by examining CSS in dev tools when we examine the website prior to the changes in this PR:

> Screen Shot 2023-08-07 at 17 52 23

### Related

@aliok did a great job analyzing the situation for [tag-contributor-strategy](https://github.com/cncf/tag-contributor-strategy), though the situation was slightly different. For details, see https://github.com/cncf/tag-contributor-strategy/pull/399.

/cc @nate-double-u @caniszczyk @cjyabraham

### CODE REVIEW

**Comment by chalin** [comment]
(I'll fix the DCO soon.)

**Review by cjyabraham — APPROVED** [review]
Looks good. Thanks.

**Comment by chalin** [comment]
Thanks for the review Chris. I'm unsure that the informal review policy is here, but with one approval I'm going merge and continue working on the Docsy upgrade. Comments are still welcome.

**Comment by chalin** [comment]
For the record, both the original build of this PR and the build of the `main` branch (post merge) required that the cache be cleared (due to git submodule changes). I've done that in both cases, and the `main` build is green again:

> image

**Pull request merged**
