### PR TITLE
Add Green Scraper project

### PR DESCRIPTION
**Pull request by guidemetothemoon**
Add Green Scraper project to the TAG ENV repo and website (ref. #345).
FYI @wrkode @Al-HusseinHameedJasim

P.S. The link validation error from the build will be fixed once this PR is merged.

### CODE REVIEW

**Review by leonardpahlke — APPROVED** [review]
LGTM

**Comment by leonardpahlke** [comment]
@wrkode @Al-HusseinHameedJasim — are you both on board being the project leads?

**Comment by guidemetothemoon** [comment]
@leonardpahlke I got confirmation from both in the tracking issue: https://github.com/cncf/tag-env-sustainability/issues/345#issuecomment-1986851922
But, of course, please reach out if situation has changed since, @wrkode @Al-HusseinHameedJasim 🙌

**Comment by wrkode** [comment]
> @leonardpahlke I got confirmation from both in the tracking issue: [#345 (comment)](https://github.com/cncf/tag-env-sustainability/issues/345#issuecomment-1986851922) But, of course, please reach out if situation has changed since, @wrkode @Al-HusseinHameedJasim 🙌

Dear @guidemetothemoon and @leonardpahlke, due to a change in circumstances, I'm stepping down as co-lead on this. There's too much lack clarity in immediate and future availability and I must prioritize my active commitments.

**Pull request merged**
