### PR TITLE
Add TAG co-chairs to github/settings file to maintain repository

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

/cc @amye @catblade @mkorbi

### CODE REVIEW

**Comment by leonardpahlke** [comment]
PR to update the README: https://github.com/cncf/tag-env-sustainability/pull/40

**Comment by catblade** [comment]
Would request not to remove others who can help maintain until we discuss.

Move chairs to a different section, label chairs, make admins.

**Comment by leonardpahlke** [comment]
IMHO there is currently not so much work that we could not handle, besides, the list is somewhat random... If the TAG grows and TL or other roles have been introduced, an expansion of the list would make sense, I think... (assigning responsibility: isn't this one of the reasons why we have roles?)

@mkorbi wdyt

**Comment by catblade** [comment]
I think having the community help is useful.  The people here are those who have already put themselves forward to help, and I desire to be as inclusive as possible.

**Comment by mkorbi** [comment]
I think we have to adjust the roles, reducing privileges to what those roles are actually required to do. For that, we have to setup our governance.

**Comment by catblade** [comment]
LGTM

**Comment by mkorbi** [comment]
lgtm

**Pull request merged**
