### PR TITLE
Move landscape to website

### PR DESCRIPTION
**Pull request by leonardpahlke**
ref slack discussion: https://cloud-native.slack.com/archives/C03F270PDU6/p1683669353680659

### CODE REVIEW

**Review by catblade — APPROVED** [review]
Looks great

**Comment by leonardpahlke** [comment]
@cjyabraham we are using [mermaid.js](https://mermaid.js.org/) to create diagrams. [mermaid.js is supported by github](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) in markdown files. Is it possible to enable it for our website? 
Quick search found this: https://discourse.gohugo.io/t/use-mermaid-with-code-fences/17211

right now the mermaid code block does not render (see screenshot)
Screenshot by Dropbox Capture

**Comment by nikimanoledaki** [comment]
I hope this is not too late but you could keep the git history if you use [git mv <path>/<file> <path>/<file>](https://git-scm.com/docs/git-mv) rather than moving the file manually :)

**Comment by leonardpahlke** [comment]
Thanks, yes! Will do tomorrow

**Comment by cjyabraham** [comment]
Hi @leonardpahlke, sure I could investigate mermaid support... want to create an issue for me for that?

**Comment by leonardpahlke** [comment]
> Hi @leonardpahlke, sure I could investigate mermaid support... want to create an issue for me for that?

Awesome, thanks @cjyabraham ! issue: https://github.com/cncf/tag-env-sustainability/issues/101

**Pull request merged**
